### ISSUE TITLE
Unable to download org.flowable:flowable-external-job-rest:6.7.2

### ISSUE THREAD

**Issue by konyashkina** [cuba-platform/cuba-sdk#102]
Cuba SDK  1.2.8
nexus-3.40.1-01
jmix-dependencies-1.4.0 
OS Windows 10 Pro

`sdk>import C:/CUBA_SDK/jmix-dependencies-1.4.0.zip`

**ER:** 
```
 Unzip archive                                                                                100.00%
 Uploading                                                                                    100.00%
```

**AR:** 
```
Unzip archive                                                                                100.00%
Uploading org.flowable:flowable-common-rest:6.7.2                                             11.44%
FAILURE: Command execution failed with an exception.
```

* What went wrong:
 Unable to download org.flowable:flowable-external-job-rest:6.7.2

`java.lang.IllegalStateException: Unable to download org.flowable:flowable-external-job-rest:6.7.2
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.artifactPath(GradleArtifactManagerImpl.kt:282)
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.upload(GradleArtifactManagerImpl.kt:243)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:173)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:40)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl.upload(ComponentManagerImpl.kt:168)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.upload(ImportCommand.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.run(ImportCommand.kt:78)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)`

**Comment by konyashkina** [comment]
Retested: 
All source SDK repositories are removed, exept sdk-local. 
New target repository created.
Unzip jmix-dependencies-1.4.0.zip archive = successfully.

**AR:** 
```
Uploading com.google.protobuf:protobuf-bom:3.19.4                                                  0.62%
FAILURE: Command execution failed with an exception.

* What went wrong:
> Unable to download org.apache.commons:commons-text:1.10.0
```

_stacktrace_
```
java.lang.IllegalStateException: Unable to download org.apache.commons:commons-text:1.10.0
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.artifactPath(GradleArtifactManagerImpl.kt:282)
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.upload(GradleArtifactManagerImpl.kt:243)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:173)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:40)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl.upload(ComponentManagerImpl.kt:168)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.upload(ImportCommand.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.run(ImportCommand.kt:78)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)```
