### ISSUE TITLE
IllegalStateException occurs after running the `sdk` command

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba-sdk#37]
### Environment

- Plugin version: 0.1-SNAPSHOT

### Description of the bug or enhancement

1. Run CUBA CLI
2. Run `sdk` command

AR: `sdkProperties.getProperty(property) must not be null` exception occurs.
Also, the same exception occurs after running the following commands: `sdk cleanup`, `sdk start`, `sdk repository list`, `sdk remove addon`.

Stacktrace
```
java.lang.IllegalStateException: sdkProperties.getProperty(property) must not be null
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.getProperty(SdkSettingsHolderImpl.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolder$DefaultImpls.get(SdkSettingsHolder.kt:43)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.get(SdkSettingsHolderImpl.kt:32)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.nexus.NexusManagerImpl.isLocal(NexusManagerImpl.kt:31)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.StartCommand.run(StartCommand.kt:27)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.commands.AbstractCommand.execute(AbstractCommand.kt:52)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.evalCommand(ShellCli.kt:135)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.run(ShellCli.kt:118)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.EntryPointKt.m
```

**Comment by Mihail063** [comment]
1. Run `repository list` command 

AR: `java.lang.IllegalStateException: sdkProperties.getProperty(property) must not be null` exception occurs.
Also, the same exception occurs after running `repository list source` command.

Stacktrace
```
java.lang.IllegalStateException: sdkProperties.getProperty(property) must not be null
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.getProperty(SdkSettingsHolderImpl.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolder$DefaultImpls.get(SdkSettingsHolder.kt:43)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.get(SdkSettingsHolderImpl.kt:32)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManagerImpl.isOnline(RepositoryManagerImpl.kt:173)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.ListRepositoryCommand.run(ListRepositoryCommand.kt:47)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:139)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:125)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:106)
```
