### ISSUE TITLE
IllegalStateException occurs after trying to remove a sdk repository

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba-sdk#40]
### Environment

- Plugin version: 0.1-SNAPSHOT

### Description of the bug or enhancement

1. Run CUBA CLI
2. Add a new sdk repository
3. Run `sdk repository remove sdk` command
4. Select the added repository

AR: `java.lang.IllegalStateException:sdkProperties.getProperty(property) must not be null` occurs 

Stacktrace
```
java.lang.IllegalStateException: sdkProperties.getProperty(property) must not be null
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.getProperty(SdkSettingsHolderImpl.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolder$DefaultImpls.get(SdkSettingsHolder.kt:43)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.get(SdkSettingsHolderImpl.kt:32)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManagerImpl.removeRepository(RepositoryManagerImpl.kt:132)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManager$DefaultImpls.removeRepository$default(RepositoryManager.kt:30)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.RemoveRepositoryCommand.removeRepository(RemoveRepositoryCommand.kt:57)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.RemoveRepositoryCommand.run(RemoveRepositoryCommand.kt:53)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.commands.AbstractCommand.execute(AbstractCommand.kt:52)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.evalCommand(ShellCli.kt:135)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.ShellCli.run(ShellCli.kt:118)
        at com.haulmont.cuba.cli/com.haulmont.cuba.cli.EntryPointKt.main(EntryPoint.kt:114)
```

**Comment by Mihail063** [comment]
1. Add a new target repository
2. Run `repository remove target` command
3. Select the added repository

AR: `java.lang.IllegalStateException:sdkProperties.getProperty(property) must not be null` exception occurs

Stacktrace
```
java.lang.IllegalStateException: sdkProperties.getProperty(property) must not be null
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.getProperty(SdkSettingsHolderImpl.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolder$DefaultImpls.get(SdkSettingsHolder.kt:43)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.get(SdkSettingsHolderImpl.kt:32)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManagerImpl.removeRepository(RepositoryManagerImpl.kt:148)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManager$DefaultImpls.removeRepository$default(RepositoryManager.kt:30)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.RemoveRepositoryCommand.removeRepository(RemoveRepositoryCommand.kt:59)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.RemoveRepositoryCommand.run(RemoveRepositoryCommand.kt:54)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:139)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:125)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:106)
```

**Comment by Mihail063** [comment]
Bug still reproduce with exception:
```
java.lang.IllegalStateException: sdkProperties.getProperty(property) must not be null
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.getProperty(SdkSettingsHolderImpl.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolder$DefaultImpls.get(SdkSettingsHolder.kt:43)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.SdkSettingsHolderImpl.get(SdkSettingsHolderImpl.kt:32)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManagerImpl.removeRepository(RepositoryManagerImpl.kt:148)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManager$DefaultImpls.removeRepository$default(RepositoryManager.kt:30)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.RemoveRepositoryCommand.removeRepository(RemoveRepositoryCommand.kt:63)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.RemoveRepositoryCommand.run(RemoveRepositoryCommand.kt:58)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)
```
