### ISSUE TITLE
SDK saved remote repository with empty or incorrectly URL 

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba-sdk#53]
### Environment

- Plugin version: 0.3-SNAPSHOT

### Description of the bug or enhancement

1. Run the SDK 
2. Run the `repository add source` command
3. Enter any repository name
4. Select the remote repository
5. Enter an empty URL
6. enter no to the question "Is repository authentication required?"
7. Run `repository list` command

AR:  Repository was saved without URL and list of repository shown with the exception.

Also, the same exception occurs after adding repository with the incorrect URL
Stacktrace 
```
java.net.MalformedURLException: no protocol:
        at java.base/java.net.URL.<init>(URL.java:627)
        at java.base/java.net.URL.<init>(URL.java:523)
        at java.base/java.net.URL.<init>(URL.java:470)
        at fuel/com.github.kittinunf.fuel.core.Encoding.createUrl(Encoding.kt:69)
        at fuel/com.github.kittinunf.fuel.core.Encoding.access$createUrl(Encoding.kt:10)
        at fuel/com.github.kittinunf.fuel.core.Encoding$encoder$1.invoke(Encoding.kt:45)
        at fuel/com.github.kittinunf.fuel.core.Encoding$encoder$1.invoke(Encoding.kt:10)
        at fuel/com.github.kittinunf.fuel.core.Encoding$request$2.invoke(Encoding.kt:57)
        at fuel/com.github.kittinunf.fuel.core.Encoding$request$2.invoke(Encoding.kt:10)
        at kotlin.stdlib/kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at fuel/com.github.kittinunf.fuel.core.Encoding.getRequest(Encoding.kt)
        at fuel/com.github.kittinunf.fuel.core.FuelManager.request(FuelManager.kt:66)
        at fuel/com.github.kittinunf.fuel.Fuel$Companion.request(Fuel.kt:130)
        at fuel/com.github.kittinunf.fuel.Fuel$Companion.head(Fuel.kt:111)
        at fuel/com.github.kittinunf.fuel.Fuel$Companion.head$default(Fuel.kt:110)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.RepositoryManagerImpl.isOnline(RepositoryManagerImpl.kt:160)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.repository.ListRepositoryCommand.run(ListRepositoryCommand.kt:46)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)
```

**Comment by Mihail063** [comment]
Bug still reproduce for target repository and when entering an empty login and password
