### ISSUE TITLE
SDK archive is not imported into the current SDK in which a local repository was created if the imported sdk has a local repository with the same characteristics

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba-sdk#59]
### Environment

- Plugin version: 0.3-SNAPSHOT

### Description of the bug or enhancement

1. Add local repository 
2. Resolve any addon (for example dashboard)
3. Run the `export` command
4. Exit from SDK
5. Save the exported archive in the other folder and clean all cache
6. Run SDK
7. Add a new local repository with the same name and path as the repository from the previous step
8. Import the exported SDK from the previous step

AR: Archive was not imported with exception
```
java.net.MalformedURLException: no protocol: /C:\Users\silkin\.m2\repositoryjavax/inject/javax.inject/1/javax.inject-1.jar
        at java.base/java.net.URL.<init>(URL.java:627)
        at java.base/java.net.URL.<init>(URL.java:523)
        at java.base/java.net.URL.<init>(URL.java:470)
        at fuel/com.github.kittinunf.fuel.core.Encoding.createUrl(Encoding.kt:69)
        at fuel/com.github.kittinunf.fuel.core.Encoding.access$createUrl(Encoding.kt:10)
        at fuel/com.github.kittinunf.fuel.core.Encoding$encoder$1.invoke(Encoding.kt:45)
        at fuel/com.github.kittinunf.fuel.core.Encoding$encoder$1.invoke(Encoding.kt:10)
        at fuel/com.github.kittinunf.fuel.core.Encoding$request$2.invoke(Encoding.kt:57)
        at fuel/com.github.kittinunf.fuel.core.Encoding$request$2.invoke(Encoding.kt:10)
        at kotlin.stdlib/kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at fuel/com.github.kittinunf.fuel.core.Encoding.getRequest(Encoding.kt)
        at fuel/com.github.kittinunf.fuel.core.FuelManager.request(FuelManager.kt:66)
        at fuel/com.github.kittinunf.fuel.Fuel$Companion.request(Fuel.kt:130)
        at fuel/com.github.kittinunf.fuel.Fuel$Companion.head(Fuel.kt:111)
        at fuel/com.github.kittinunf.fuel.Fuel$Companion.head$default(Fuel.kt:110)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl.alreadyUploaded(ComponentManagerImpl.kt:141)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl.alreadyUploaded(ComponentManagerImpl.kt:128)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl.access$alreadyUploaded(ComponentManagerImpl.kt:38)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:156)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:38)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl.upload(ComponentManagerImpl.kt:154)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.upload(ImportCommand.kt:97)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.run(ImportCommand.kt:73)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)
```

**Comment by Mihail063** [comment]
Bug still reprodice with exception
```
java.lang.IllegalStateException: Unable to download com.haulmont.addon.dashboard:dashboard-core:3.2.2:db@zip
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.getOrDownloadArtifactFile(GradleArtifactManagerImpl.kt:257)
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.upload(GradleArtifactManagerImpl.kt:194)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:162)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl$upload$1.accept(ComponentManagerImpl.kt:37)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ComponentManagerImpl.upload(ComponentManagerImpl.kt:157)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.upload(ImportCommand.kt:102)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.ImportCommand.run(ImportCommand.kt:78)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)
```

**Comment by Mihail063** [comment]
Steps to reproduce the bug
1. Add local repository
2. Resolve any addon (for example dashboard)
3. Run the `export` command
4. Exit from SDK
5. Save the exported archive in the other folder and clean all cache
6. Run SDK
7. Add a new local `target` repository with the same name and path as the repository from the previous step
8. Import the exported SDK from the previous step

AR: Archive was not imported with exception
