### ISSUE TITLE
Cuba component is not exported with exception

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba-sdk#61]
### Environment

- Plugin version: 0.3-SNAPSHOT

### Description of the bug or enhancement

1. Install any version of the cuba component
2. Export the installed cuba component

AR: InvalidPathException occurs 

Stacktrace
```
java.nio.file.InvalidPathException: Illegal char <:> at index 48: C:\Users\silkin\.haulmont\cli\sdk\gradle\cache\C:\Users\silkin\.haulmont\cli\sdk\gradle\raw\gradle\gradle\5.6.4\gradle-5.6.4.zip
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.readFromCache(GradleArtifactManagerImpl.kt:185)
        at com.haulmont.cuba.cli.plugin.sdk.gradle/com.haulmont.cli.plugin.sdk.gradle.GradleArtifactManagerImpl.getOrDownloadArtifactFile(GradleArtifactManagerImpl.kt:251)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.services.ImportExportServiceImpl.export(ImportExportServiceImpl.kt:63)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.AbstractExportCommand.run(AbstractExportCommand.kt:38)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.AbstractComponentExportCommand.run(AbstractComponentExportCommand.kt:81)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)
```

**Comment by zaharchenko-evgeny** [comment]
fixed in https://github.com/cuba-platform/cuba-sdk/issues/62
