### ISSUE TITLE
ConcurrentModificationException in cleanup command

### ISSUE THREAD

**Issue by lovtsovaik** [cuba-platform/cuba-sdk#83]
**Steps**

- Run sdk
- resolve some addons
- run `cleanup` command

AR: 
some addons are removed (not all), exception occurs:
```
java.util.ConcurrentModificationException
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
        at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.CleanCommand.cleanup(CleanCommand.kt:95)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.CleanCommand.run(CleanCommand.kt:55)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)
```

see [cleanup-log.txt](https://github.com/cuba-platform/cuba-sdk/files/8159429/cleanup-log.txt) to see the working history (no error at the end)

**Comment by lovtsovaik** [comment]
verified
