### ISSUE TITLE
Addon installation error: Index 0 out of bounds for length 0 

### ISSUE THREAD

**Issue by konyashkina** [cuba-platform/cuba-sdk#98]
Follow the instructions: https://docs.jmix.ru/jmix/isolated-network.html till install jmix-addon.
Try `install jmix-addon`  or `install jmix-addon email:1.3.1`, ` install jmix-addon maps:1.3.1` , ` install jmix-addon reports:1.3.1 `

**ER:** Jmix addon is installed successfully.

**AR:** Command execution failed with an exception.

```
* What went wrong:
> Index 0 out of bounds for length 0

* Try:
Run `stacktrace` command to get full stack trace or use --stacktrace option.

sdk>stacktrace
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at com.haulmont.cuba.cli.plugin.sdk.components.cuba/com.haulmont.cli.plugin.sdk.component.cuba.providers.JmixAddonProvider.initAddonTemplate(JmixAddonProvider.kt:58)
        at com.haulmont.cuba.cli.plugin.sdk.components.cuba/com.haulmont.cli.plugin.sdk.component.cuba.providers.JmixAddonProvider.components(JmixAddonProvider.kt:54)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.BaseComponentCommand.providerSearchContext$cuba_sdk(BaseComponentCommand.kt:392)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.InstallComponentCommand.createSearchContext(InstallComponentCommand.kt:34)
        at com.haulmont.cuba.cli.plugin.sdk/com.haulmont.cuba.cli.plugin.sdk.commands.artifacts.BaseInstallCommand.run(BaseInstallCommand.kt:36)
        at com.haulmont.cli.core/com.haulmont.cli.core.commands.AbstractCommand.execute(AbstractCommand.kt:37)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.evalCommand(ShellCli.kt:138)
        at com.haulmont.cli.core/com.haulmont.cli.core.ShellCli.run(ShellCli.kt:124)
        at com.haulmont.cli.core/com.haulmont.cli.core.EntryPointKt.main(EntryPoint.kt:116)
```

**Comment by konyashkina** [comment]
Tested on cuba-sdk-0.3-SNAPSHOT-windows
with Jmix 1.3.2
